### ISSUE TITLE
availability of FOSS APK

### ISSUE THREAD

**Issue by IzzySoft** [JunkieLabs/sensify-android#8]
Would you consider making a F/LOSS APK available (e.g. by tagging [releases](https://github.com/JunkieLabs/sensify-android/releases) and attaching it there) for those without PlayStore access, ideally without the two analytics trackers (Crashlytics, Firebase Analytics)? Thanks in advance!

**Comment by IzzySoft** [comment]
any cance, @nirajprakash ?

**Comment by nirajprakash** [comment]
@IzzySoft, working on it. I'll update you soon.

**Comment by IzzySoft** [comment]
Thanks a lot – looking forward to that :star_struck:

**Comment by nirajprakash** [comment]
@IzzySoft, added one release,
 https://github.com/JunkieLabs/sensify-android/releases/

**Comment by IzzySoft** [comment]
Thanks a lot! But `app-release-unsigned-signed.apk` suggests the APK is, hm, unsigned? That means the "end user" is lost as it doesn't install this way. Would you mind attaching a signed APK instead?

**Comment by IzzySoft** [comment]
Thanks a lot! The `unsigned` got me confused initially, the APK is indeed signed. BUT:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Google Ads (/com/google/ads): Ads,NonFreeDep
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

7 offenders.
```

is not really FOSS (5 of these libs are non-free, the other 2 at least use non-free network services). Not sure why any of them would be needed to visualize sensors. Maybe you could establish a "foss build flavor" having the offenders removed?

**Comment by nirajprakash** [comment]
Crashlytics is used for crash checks. And analytics for the understanding of app usage to publish new updates. Those are not used for visualization. 
Can you tell me specifically, where you want to use this app?

**Comment by IzzySoft** [comment]
Sure I can. I want to make it available and easy to discover/update in the FOSS world and, for "privacy-aware", outside of Google's walled garden – where it (due to the non-free components) cannot enter e.g. F-Droid.org. For that purpose (apps which are per-se FOSS but somehow cannot enter F-Droid.org) I run a well-known third-party F-Droid repo (in fact the largest one after F-Droid.org itself) at https://apt.izzysoft.de/fdroid (currently covering more than 1k apps) and would like to add your app there. While my inclusion criteria are a bit more lenient than those at F-Droid.org, there are still some limits: I can close an eye or two, but I do not have 7 eyes :see_no_evil:

So a FOSS flavor would be highly appreciated. Considering that probably more than 95% of your users will still install the app from Play Store, the loss of analytics wouldn't really hurt. If you'd still want some, be welcome to take a look at [alternatives I collected](https://gitlab.com/-/snippets/1896503#acceptable-analytics) – and btw, there are also some for Firebase itself, like [appwrite](https://github.com/appwrite/appwrite) and [Supabase](https://supabase.com/), just mentioned above the linked section. For crash reporting, a good choice would e.g. be [ACRA](https://github.com/ACRA/acra) with only its crash reporter configured to ask the user sending the details by mail (presenting the details and offering a button to open with their mail app for sending). Us privacy folks love transparency, so we want to see what we send :wink: For other analytics, e.g. a (self-hosted) [Sentry.io](https://sentry.io/) (configured opt-in, i.e. first getting the user's consent before enabling it) should be fine. I guess the remaining libraries are just dragged in as dependencies – so the list would probably be cleared after replacing Crashlytics and Firebase Analytics, unless you use Firebase directly for other purposes.

While the "easiest" way would probably be replacing these in general, it could also be done using "build flavors" (e.g. one with Crashlytics/Firebase Analytics to ship to Google Play, and one using ACRA/Sentry for the "privacy folks").

Thanks for considering – and thanks in advance should you implement this :star_struck:

**Comment by nirajprakash** [comment]
For this one, I will add a different flavor.

**Comment by nirajprakash** [comment]
@IzzySoft, check this one.. https://github.com/JunkieLabs/sensify-android/releases/tag/Sensify_FOSS_2023.03.05_02-07

I removed google plugins.

**Comment by IzzySoft** [comment]
Thanks – that looks perfect! All "offenders" are gone! :partying_face:

Adding it now to my repo. I see you're using a different tag for the FOSS release. Could the name of that tag maybe reflect the `versionName`, like being `v3.0.12-foss`? That would make it easier for my updater to detect new releases (without downloading and checking the file each time). For now I've restricted it to only consider tag names matching the regular expression `/Sensify_FOSS_.+/` which should work but would still rely on one more check (alleged timestamp of the file), which in the past *sometimes* failed and I still have no idea why – maybe timezone stuff).

That said, your app should [show up here](https://apt.izzysoft.de/fdroid/index/apk/io.sensify.sensor.foss) around 7 pm UTC (with the next sync). If you like what you see, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there from e.g. your Readme. And if you want to stay in control how your app is presented here, I gladly open a PR sending you the metadata I've set up in Fastlane format (see my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for details on how to build on that, e.g. adding per-release changelogs or support other locales).

Thanks a lot for your app, and especially for providing the FOSS build! :star_struck:

**Comment by nirajprakash** [comment]
I will try to link the app's version with the GitHub action.
For now, I have used this format for release tags: 

Sensify_FOSS_$(date +"%Y.%m.%d_%H-%M").

**Comment by IzzySoft** [comment]
That's what I try to match on currently (and hope it works). Ideally I can match on something containing either `versionName` (using [semantic versioning](https://semver.org/)) or `versionCode`. For both I can clearly say what's already available in my repo and whether the latest tag should be an update (`tag > version`) or not **without** having to dig deeper (check file dates etc).

We can of course first see if it works as-is (it should); if the other means too much trouble for you, we certainly can do with what we have now. Most important is you have some indicator (like currently `FOSS`) in the tag name (or file name) so I do not accidentally pick the wrong APK :smile:

**Comment by IzzySoft** [comment]
@nirajprakash I see you've just closed this, but there was no new release yet. Sure it works without adjustments? I thought we first wanted to verify.
